/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/simulation/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start the simulation by creating a cluster
         * @description Creates a new cluster from the supplied configuration and returns its
         *     initial state. Equivalent in effect to `POST /api/v1/clusters`.
         */
        post: operations["startSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset the simulation
         * @description Deletes every active cluster.
         */
        post: operations["resetSimulation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the state of all clusters */
        get: operations["getSimulationState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get per-cluster metrics
         * @description Returns a map of cluster ID to that cluster's metrics snapshot.
         */
        get: operations["getSimulationMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all clusters */
        get: operations["listClusters"];
        put?: never;
        /** Create a cluster */
        post: operations["createCluster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a cluster */
        delete: operations["deleteCluster"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a cluster's state */
        get: operations["getClusterState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/convergence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check convergence
         * @description Reports whether all online replicas agree on every key.
         */
        get: operations["getConvergence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/suspicion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get phi-accrual suspicion levels
         * @description Reports each node's phi-accrual failure-suspicion level.
         */
        get: operations["getSuspicion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/placement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the preference list for a key
         * @description Returns the consistent-hashing preference list for a key.
         */
        get: operations["getPlacement"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List pending conflicts
         * @description Lists parked (manual) multi-leader conflicts awaiting a choice.
         */
        get: operations["listConflicts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/conflicts/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a pending conflict */
        post: operations["resolveConflict"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch cluster configuration
         * @description Applies supported config patches to a live cluster. Currently
         *     `replication_mode` is supported and is only valid for `single_leader`
         *     clusters.
         */
        patch: operations["patchClusterConfig"];
        trace?: never;
    };
    "/api/v1/clusters/{id}/linearizable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check linearizability
         * @description Checks the recorded op history against a linearizable register model.
         */
        get: operations["checkLinearizable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/invariants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check invariants
         * @description Reports the always-on invariants (convergence + linearizability).
         */
        get: operations["checkInvariants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/anti-entropy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run an anti-entropy round
         * @description Runs a Merkle-tree anti-entropy round and reports the divergent keys
         *     exchanged plus whether the cluster converged.
         */
        post: operations["runAntiEntropy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/reconfigure/add-node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Safely add a node (leaderless)
         * @description Performs a safe two-phase leaderless membership change (no
         *     quorum-overlap gap) and reports the transition.
         */
        post: operations["safeAddNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/write": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Write a key */
        post: operations["write"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a key */
        get: operations["read"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/kv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a key */
        delete: operations["deleteKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/write-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Write a batch of keys
         * @description Writes multiple entries. When `atomic` is true the batch is applied
         *     all-or-nothing on a single-leader cluster; otherwise each entry is
         *     written independently and a per-entry result/error is returned.
         */
        post: operations["writeBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a node */
        post: operations["addNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a node */
        delete: operations["removeNode"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause a node */
        post: operations["pauseNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a node */
        post: operations["resumeNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}/clock-skew": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a node's clock skew
         * @description Injects a physical-clock offset (ms) on a node.
         */
        post: operations["setClockSkew"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a node's replication log */
        get: operations["getNodeLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/nodes/{nodeId}/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a node's key-value store */
        get: operations["getNodeStore"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/network/partition": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inject a network partition
         * @description Partitions the cluster into two disjoint groups of nodes.
         */
        post: operations["injectPartition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/network/partition/{partId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Heal a network partition */
        delete: operations["healPartition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/network/latency": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set one-way link latency */
        post: operations["setLatency"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/network/drop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set packet-drop rate on a link */
        post: operations["setDrop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/network/faults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear all network faults
         * @description Removes all latency, drop-rate and partition overrides.
         */
        delete: operations["clearFaults"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/demo/read-your-writes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Read-your-writes demo
         * @description Writes on one node and immediately reads the write back from a lagging
         *     replica, so the demo shows a violation when it occurs.
         */
        post: operations["demoReadYourWrites"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/demo/monotonic-reads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Monotonic-reads demo
         * @description After the client sees a newer value on a fresh node, a read from a
         *     lagging replica may return the older value — reads going backward.
         */
        post: operations["demoMonotonicReads"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clusters/{id}/demo/consistent-prefix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consistent-prefix demo
         * @description Writes an ordered sequence and reads it back, reporting the observed
         *     order. Single-leader guarantees the prefix; multi-leader reordering can
         *     break it.
         */
        post: operations["demoConsistentPrefix"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List built-in scenarios */
        get: operations["listScenarios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scenarios/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a scenario
         * @description Provisions and runs the named scenario, returning the resulting cluster state.
         */
        post: operations["runScenario"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/2pc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Two-phase commit demo */
        get: operations["demoTwoPC"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/mvcc": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** MVCC snapshot-read demo */
        get: operations["demoMVCC"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/wal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Write-ahead-log durability demo */
        get: operations["demoWAL"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/swim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** SWIM membership demo */
        get: operations["demoSWIM"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/paxos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paxos single-decree demo */
        get: operations["demoPaxos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/demos/detsim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deterministic-simulation demo */
        get: operations["demoDetSim"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: string;
        };
        StatusMessage: {
            /** @example ok */
            status?: string;
        };
        /** @enum {string} */
        ReplicationStrategy: "single_leader" | "multi_leader" | "leaderless" | "raft";
        /** @enum {string} */
        ReplicationMode: "async" | "sync" | "semi_sync";
        /** @enum {string} */
        ConflictResolver: "lww" | "vector_clock" | "crdt" | "manual";
        /** @description Parameters for creating a new cluster. */
        ClusterConfig: {
            strategy: components["schemas"]["ReplicationStrategy"];
            /**
             * @description Number of nodes. Defaults to 3 (5 for leaderless) when < 1.
             * @example 3
             */
            node_count?: number;
            replication_mode?: components["schemas"]["ReplicationMode"];
            conflict_resolver?: components["schemas"]["ConflictResolver"];
            /** @description Replication factor N (leaderless). */
            quorum_n?: number;
            /** @description Write quorum W (leaderless). */
            quorum_w?: number;
            /** @description Read quorum R (leaderless). */
            quorum_r?: number;
            /** @description Split nodes across N regions with inter-region latency. */
            regions?: number;
            inter_region_latency_ms?: number;
            /**
             * @description Region-aware quorum (leaderless).
             * @enum {string}
             */
            consistency_level?: "quorum" | "local_quorum" | "each_quorum";
            /** @enum {string} */
            read_repair_mode?: "async" | "sync" | "digest";
            /** @description Enable sloppy quorum with hinted handoff (default on). */
            sloppy_quorum?: boolean;
        };
        /**
         * @description Supported live-config patches. Only `replication_mode` is applied
         *     (single-leader clusters only); other keys are ignored.
         */
        ClusterConfigPatch: {
            replication_mode?: components["schemas"]["ReplicationMode"];
        };
        /** @description JSON-serialisable snapshot of a cluster. */
        ClusterState: {
            id: string;
            config: components["schemas"]["ClusterConfig"];
            node_ids: string[];
            leader_id?: string;
            nodes: {
                [key: string]: components["schemas"]["NodeStatus"];
            };
            metrics: components["schemas"]["ClusterMetrics"];
            /** Format: date-time */
            created: string;
            partitions: {
                [key: string]: components["schemas"]["Partition"];
            };
            /**
             * Format: int64
             * @description Count of back-pressure drops (full queues).
             */
            dropped_messages?: number;
            /** @description nodeID -> region index (geo). */
            node_regions?: {
                [key: string]: number;
            };
        };
        /** @description Metrics snapshot for a cluster (shape depends on strategy). */
        ClusterMetrics: {
            [key: string]: unknown;
        };
        /** @description A network partition between two groups of nodes. */
        Partition: {
            id?: string;
            group_a?: {
                [key: string]: boolean;
            };
            group_b?: {
                [key: string]: boolean;
            };
        };
        NodeStatus: {
            id?: string;
            cluster_id?: string;
            strategy?: components["schemas"]["ReplicationStrategy"];
            role?: string;
            state?: string;
            /** Format: int64 */
            commit_index?: number;
            /** Format: int64 */
            last_applied?: number;
            leader_id?: string;
            peers?: string[];
            /** Format: int64 */
            lag?: number;
        };
        NodeSuspicion: {
            /** Format: double */
            phi?: number;
            suspected?: boolean;
        };
        /** @description One entry in a node's replication log. */
        LogEntry: {
            [key: string]: unknown;
        };
        /** @description A stored key-value entry with its causal metadata. */
        KVEntry: {
            key?: string;
            /**
             * Format: byte
             * @description Base64-encoded value bytes.
             */
            value?: string;
            /** @description Vector clock (nodeID -> counter). */
            vclock?: {
                [key: string]: number;
            };
            /**
             * Format: int64
             * @description UnixNano write time.
             */
            timestamp?: number;
            node_id?: string;
            tombstone?: boolean;
            /** Format: int64 */
            version?: number;
        };
        WriteRequest: {
            key: string;
            value?: string;
            client_id?: string;
            /** @description Target node; defaults to the leader / first node. */
            target_node_id?: string;
        };
        BatchWriteRequest: {
            entries: components["schemas"]["WriteRequest"][];
            client_id?: string;
            /** @description All-or-nothing on a single-leader cluster. */
            atomic?: boolean;
        };
        WriteResult: {
            entry?: components["schemas"]["KVEntry"];
            node_id?: string;
        };
        ReadResult: {
            entry?: components["schemas"]["KVEntry"];
            node_id?: string;
        };
        AtomicBatchResult: {
            /** @example true */
            atomic?: boolean;
            entries?: components["schemas"]["KVEntry"][];
        };
        NonAtomicBatchResult: {
            /** @description Per-entry WriteResult on success or an error object on failure. */
            results: (components["schemas"]["WriteResult"] | components["schemas"]["BatchEntryError"])[];
        };
        BatchEntryError: {
            error?: string;
            key?: string;
        };
        PendingConflict: {
            node_id?: string;
            key?: string;
            local_value?: string;
            remote_value?: string;
        };
        ResolveConflictRequest: {
            node_id: string;
            key: string;
            /** @enum {string} */
            choice: "local" | "remote";
        };
        ClockSkewRequest: {
            /**
             * Format: int64
             * @description Physical-clock offset in milliseconds.
             */
            ms: number;
        };
        PartitionRequest: {
            group_a: string[];
            group_b: string[];
        };
        LatencyRequest: {
            from: string;
            to: string;
            ms: number;
        };
        DropRequest: {
            from: string;
            to: string;
            /**
             * Format: double
             * @description Packet-drop probability in [0, 1].
             */
            rate: number;
        };
        ConvergenceReport: {
            cluster_id?: string;
            converged?: boolean;
            keys?: number;
            diverged?: components["schemas"]["KeyDivergence"][];
            note?: string;
        };
        KeyDivergence: {
            key?: string;
            /** @description nodeID -> value | "<tombstone>" | "<absent>". */
            values?: {
                [key: string]: string;
            };
        };
        LinearizabilityReport: {
            cluster_id?: string;
            ops?: number;
            linearizable?: boolean;
            violation?: components["schemas"]["ViolationOp"];
            note?: string;
        };
        ViolationOp: {
            client_id?: string;
            /** @enum {string} */
            kind?: "read" | "write";
            key?: string;
            value?: string;
        };
        InvariantReport: {
            cluster_id?: string;
            converged?: boolean;
            linearizable?: boolean;
            ok?: boolean;
            violations?: string[];
        };
        AntiEntropyReport: {
            cluster_id?: string;
            total_keys?: number;
            divergent_keys?: string[];
            reconciled?: number;
            converged_after?: boolean;
        };
        ReconfigureReport: {
            cluster_id?: string;
            added_node?: string;
            /** @description [N, W, R] */
            old_quorum?: number[];
            /** @description [N, W, R] */
            new_quorum?: number[];
            overlap_held?: boolean;
            reconciled?: number;
            phases?: string[];
        };
        ReadYourWritesReport: {
            client_id?: string;
            write_key?: string;
            write_value?: string;
            write_node?: string;
            read_node?: string;
            write_result?: components["schemas"]["WriteResult"];
            read_result?: components["schemas"]["ReadResult"];
            consistent?: boolean;
            explanation?: string;
        };
        MonotonicReadsReport: {
            client_id?: string;
            read_node1?: string;
            read_node2?: string;
            read1?: components["schemas"]["ReadResult"];
            read2?: components["schemas"]["ReadResult"];
            monotonic?: boolean;
            explanation?: string;
        };
        ConsistentPrefixReport: {
            client_id?: string;
            write_node?: string;
            read_node?: string;
            sequence?: string[];
            observed?: string;
            writes?: components["schemas"]["WriteResult"][];
            consistent?: boolean;
            explanation?: string;
        };
        Scenario: {
            name?: string;
            strategy?: components["schemas"]["ReplicationStrategy"];
            description?: string;
            node_count?: number;
        };
        TwoPCDemoReport: {
            crash?: boolean;
            committed?: boolean;
            blocked?: boolean;
            recovered?: boolean;
            final_values?: {
                [key: string]: string;
            };
            narrative?: string[];
        };
        MVCCDemoReport: {
            narrative?: string[];
            read_at_5_found?: boolean;
            read_at_15?: string;
            read_at_25?: string;
            snapshot_stable?: boolean;
        };
        WALDemoReport: {
            mode?: string;
            acked?: number;
            durable_before_crash?: number;
            lost?: number;
            narrative?: string[];
        };
        SWIMDemoReport: {
            narrative?: string[];
            final_alive?: string[];
            final_suspect?: string[];
            final_dead?: string[];
        };
        PaxosDemoReport: {
            narrative?: string[];
            first_chosen?: string;
            second_proposed?: string;
            second_chosen?: string;
            safety_held?: boolean;
        };
        DetSimDemoReport: {
            /** Format: int64 */
            seed?: number;
            run1?: number[];
            run2?: number[];
            reproducible?: boolean;
            narrative?: string[];
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Operation conflict (e.g. unmet quorum, wrong target, paused node) */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description Cluster ID (UUID). */
        ClusterId: string;
        /** @description Node ID. */
        NodeId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    startSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterConfig"];
            };
        };
        responses: {
            /** @description Cluster created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    resetSimulation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Simulation reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example reset */
                        status?: string;
                    };
                };
            };
        };
    };
    getSimulationState: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description State snapshot of every active cluster */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        clusters?: components["schemas"]["ClusterState"][];
                    };
                };
            };
        };
    };
    getSimulationMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics keyed by cluster ID */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ClusterMetrics"];
                    };
                };
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of cluster states */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"][];
                };
            };
        };
    };
    createCluster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterConfig"];
            };
        };
        responses: {
            /** @description Cluster created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    deleteCluster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    getClusterState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cluster state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getConvergence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Convergence report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConvergenceReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getSuspicion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Suspicion levels per node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * Format: double
                         * @description Phi level above which a node is treated as failed.
                         * @example 8
                         */
                        threshold?: number;
                        nodes?: {
                            [key: string]: components["schemas"]["NodeSuspicion"];
                        };
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getPlacement: {
        parameters: {
            query?: {
                /** @description Key to place on the ring. */
                key?: string;
                /** @description Number of replicas to return. */
                n?: number;
            };
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preference list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        key?: string;
                        preference_list?: string[];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    listConflicts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending conflicts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        conflicts?: components["schemas"]["PendingConflict"][];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resolveConflict: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveConflictRequest"];
            };
        };
        responses: {
            /** @description Conflict resolved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example resolved */
                        status?: string;
                        key?: string;
                        choice?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    patchClusterConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClusterConfigPatch"];
            };
        };
        responses: {
            /** @description Updated cluster state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    checkLinearizable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Linearizability report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LinearizabilityReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    checkInvariants: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invariant report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvariantReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    runAntiEntropy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Anti-entropy report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AntiEntropyReport"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    safeAddNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reconfigure report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconfigureReport"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    write: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteRequest"];
            };
        };
        responses: {
            /** @description Write result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WriteResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    read: {
        parameters: {
            query: {
                key: string;
                client_id?: string;
                /** @description Target node; defaults to the leader / first node. */
                node_id?: string;
            };
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadResult"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteKey: {
        parameters: {
            query: {
                key: string;
                client_id?: string;
                node_id?: string;
            };
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Key deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example deleted */
                        status?: string;
                        key?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    writeBatch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchWriteRequest"];
            };
        };
        responses: {
            /** @description Batch result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtomicBatchResult"] | components["schemas"]["NonAtomicBatchResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
        };
    };
    addNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node added */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeStatus"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    removeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    pauseNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node paused */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    resumeNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setClockSkew: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClockSkewRequest"];
            };
        };
        responses: {
            /** @description Clock skew set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status?: string;
                        node?: string;
                        /** Format: int64 */
                        skew_ms?: number;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getNodeLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Log snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getNodeStore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                /** @description Node ID. */
                nodeId: components["parameters"]["NodeId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Store snapshot keyed by key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["KVEntry"];
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    injectPartition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartitionRequest"];
            };
        };
        responses: {
            /** @description Partition created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        partition_id?: string;
                    };
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    healPartition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
                partId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Partition healed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    setLatency: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LatencyRequest"];
            };
        };
        responses: {
            /** @description Latency set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    setDrop: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DropRequest"];
            };
        };
        responses: {
            /** @description Drop rate set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    clearFaults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Faults cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusMessage"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    demoReadYourWrites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-your-writes demo result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadYourWritesReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    demoMonotonicReads: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Monotonic-reads demo result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonotonicReadsReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    demoConsistentPrefix: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cluster ID (UUID). */
                id: components["parameters"]["ClusterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Consistent-prefix demo result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsistentPrefixReport"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    listScenarios: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario catalogue */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Scenario"][];
                };
            };
        };
    };
    runScenario: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Scenario name (e.g. `ReplicationLag`). */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scenario cluster created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClusterState"];
                };
            };
            404: components["responses"]["NotFound"];
            500: components["responses"]["InternalError"];
        };
    };
    demoTwoPC: {
        parameters: {
            query?: {
                /** @description When `true`, crashes the coordinator after prepare. */
                crash?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 2PC demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TwoPCDemoReport"];
                };
            };
        };
    };
    demoMVCC: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MVCC demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MVCCDemoReport"];
                };
            };
        };
    };
    demoWAL: {
        parameters: {
            query?: {
                /** @description Durability mode. */
                mode?: "buffered" | "fsync";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description WAL demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WALDemoReport"];
                };
            };
        };
    };
    demoSWIM: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SWIM demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SWIMDemoReport"];
                };
            };
        };
    };
    demoPaxos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paxos demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaxosDemoReport"];
                };
            };
        };
    };
    demoDetSim: {
        parameters: {
            query?: {
                /** @description RNG seed; the same seed reproduces the run. */
                seed?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deterministic-simulation demo report */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DetSimDemoReport"];
                };
            };
        };
    };
}
